CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS programadores (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  apelido VARCHAR(100) UNIQUE NOT NULL,
  nome VARCHAR(100) NOT NULL,
  nascimento DATE NOT NULL,
  stack TEXT[] NOT NULL
);